apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-us1i
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-bundle-tenant/appstudio/dc-metro-map-us1i@sha256:de5579b959a5502565957d869bf03c0b1bf183335160d9d6d4900e84e6c05765
        name: my-nodejs
        resources: {}
status: {}
